include:
  - project: ${GITLAB_CI_TEMPLATES_DEVOPS}
    file: '/releases/docker-1.gitlab-ci.yml'

stages:
  - build

variables:
  IMAGE_VERSION: "${CI_COMMIT_TAG}"
  KANIKO_BUILD_ARGS: "VERSION=${CI_COMMIT_TAG}"

build_image:dta:
  extends: .kaniko
  tags: ["clay-dta"]
  only:
    - tags

# .copyImage is prepared for claycontainers -> clayprodcontainers (dta -> prod)
promote_image:prod:
  stage: build
  extends: .copyImage
  tags: ["clay-prod"]
  needs:
    - build_image:dta
  only:
    - tags

# images for new subcriptions
build_image:clp-acc:
  extends: .kaniko
  tags: ["clp-acc-devops"]
  variables:
    KANIKO_CONTAINER_REGISTRY: "clpacc.azurecr.io"
  only:
    - tags

promote_image:prd:
  stage: build
  extends: .copyImage
  tags: ["clp-prd-devops"]
  variables:
    SOURCE_CONTAINER_REGISTRY: "clpacc.azurecr.io"
    SOURCE_SUBSCRIPTION_ID: "3607529b-171e-4d43-8472-a3197aeb6422"
    SOURCE_CR_RG: "default-weu"
    DESTINATION_CONTAINER_REGISTRY: "clpprd.azurecr.io"
    DESTINATION_SUBSCRIPTION_ID: "38d076e3-3c4f-491d-8e0b-a4712dd7f0a1"
    DESTINATION_CR_RG: "default-weu"
  needs:
    - build_image:clp-acc
  only:
    - tags
